# Allow compute credits usage for collaborators and anything pushed to the
# master, staging, and trying branches. (So bors can use them.)
use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' || $CIRRUS_BRANCH == 'master' || $CIRRUS_BRANCH == 'staging' || $CIRRUS_BRANCH == 'trying'

lint_task:
  container:
    image: python:3-slim
  install_script:
    - pip3 install lxml pylint
  script:
    - pylint check_versions/ generate_site/

archlinux_and_manjaro_task:
  container:
    matrix:
      - image: archlinux:latest
      - image: manjarolinux/base:latest
  install_script: pacman -Sy --noconfirm python3
  script: python3 -m check_versions
  json_artifacts:
    path: "source/*.json"

fedora_task:
  container:
    matrix:
      - image: fedora:34
      - image: fedora:35
  script: python3 -m check_versions
  json_artifacts:
    path: "source/*.json"

opensuse_task:
  container:
    matrix:
      - image: opensuse/leap:15.3
  install_script: zypper install --no-confirm python3
  script: python3 -m check_versions
  json_artifacts:
    path: "source/*.json"

debian_and_ubuntu_task:
  container:
    matrix:
      - image: debian:10
      - image: debian:11
      - image: ubuntu:18.04
      - image: ubuntu:20.04
  install_script:
    - apt-get -y update
    - apt-get -y install python3
  script: python3 -m check_versions
  json_artifacts:
    path: "source/*.json"

freebsd_task:
  freebsd_instance:
    matrix:
      - image_family: freebsd-12-2
      - image_family: freebsd-13-0
  script: python3 -m check_versions
  json_artifacts:
    path: "source/*.json"

task:
  name: CI success
  container:
    image: busybox
  depends_on:
    - lint
    - archlinux_and_manjaro
    - fedora
    - opensuse
    - debian_and_ubuntu
    - freebsd

# TODO: Generate the site on non-master branches Just To Be Sure™.
publish_task:
  only_if: $BRANCH == 'main'
  depends_on:
    - CI success
  container:
    image: debian:11
  env:
    NETLIFY_AUTH_TOKEN: ENCRYPTED[ec6da05d365917ed543e307555cbd9c618bbd41db7dee828daf7b01825adef48f547db89ead63b99418fe07a9d41b43a]
    NETLIFY_SITE_ID: ENCRYPTED[a408add4551cd62fe8a5a912569fda66b5e991dd1097a8eaf0a6479179a07a6ec3e5d9e0c67d16f61c67a6721a728a91]
  install_script:
    - apt-get -y update
    - apt-get -y install python3 python3-lxml nodejs npm
    # https://github.com/netlify/cli/issues/1870
    - npm install --unsafe-perm=true -g netlify-cli
  script:
    - python3 -m generate_site $CIRRUS_BUILD_ID
    - stat _site/index.html
    - netlify deploy --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID --dir=_site --prod
