status = [
  "lint",
  "archlinux_and_manjaro container:archlinux:latest",
  "archlinux_and_manjaro container:manjarolinux/base:latest",
  "debian_and_ubuntu container:debian:10",
  "debian_and_ubuntu container:debian:9",
  "debian_and_ubuntu container:ubuntu:16.04",
  "debian_and_ubuntu container:ubuntu:18.04",
  "debian_and_ubuntu container:ubuntu:19.10",
  "debian_and_ubuntu container:ubuntu:20.04",
  "fedora container:fedora:30",
  "fedora container:fedora:31",
  "opensuse",
  "freebsd FreeBSD:freebsd-11-3-snap",
  "freebsd FreeBSD:freebsd-12-1-snap",
  "freebsd FreeBSD:freebsd-13-0-snap",
]

delete_merged_branches = true
